config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :filter_settings
  resources :user_messages
  resources :bid_message_defaults
  devise_for :users
  resources :listings
  resources :services
  resources :reports
  resources :job_bids
  
  get 'reddit', to: "listings#reddit"
  get 'bid/:range/report', to: "reports#bids"
  
  # get '/auth/:service', to: "services#connect_service_accounts"
  get '/auth/:service/callback', to: "services#connect_service_accounts"
  
  post 'save_credentials', to: "services#create_service_credentials"
  post 'service/accounts/new', to: "services#create_service_accounts"
  
  post 'listing/bookmark', to: "listings#bookmark_toggle"
  post 'listing/filter', to: "listings#listings_search_and_filter"
  
  post 'custom_message', to: "user_messages#create_user_message"
  
  delete 'delete_custom_message', to: "user_messages#delete_user_message"
  
  get 'incoming_messages', to: "incoming_messages#all_incoming"
  
  post 'messages/viewed', to: "incoming_messages#clear_messages"
  post 'message/viewed', to: "incoming_messages#mark_as_viewed"
  
  get 'job_bid_message', to: "job_bids#bid_message"
  get 'all_listings', to: "listings#all_listings"
  
  post 'log_bid', to: "job_bids#log_bid"
  
  # Test the validity of user Oauth tokens.
  post 'token_check', to: "services#check_oauth_tokens"
  
  # Toggle won_at for bids.
  post 'bid/won', to: "job_bids#toggle_won"
  
  get 'bids/today', to: "job_bids#today_bids"
  
  root 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id         :integer          not null, primary key
#  service_id :integer
#  title      :string
#  descr      :text
#  url        :string
#  listed_at  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  identifier :string
#  expired_at :datetime
#  owner      :string
#

class Listing < ApplicationRecord
  belongs_to :service
  belongs_to :listing_bookmark
  has_many :bids
  has_and_belongs_to_many :users
  
  def self.to_csv
    CSV.generate do |csv|
      csv << Listing.attribute_names
      Listing.all.each do |l|
        csv << l.attributes.values
      end
    end
  end
end

app/controllers/listings_controller.rb
require "csv"

class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @sort_by = params[:sort_col]
    @sort_direction = params[:sort_direction]
    
    page_num = !params[:page].blank? ? params[:page] : 1
    # page_num = params[:page] || 1
    
    filters = current_user.filter_settings.all
    
    settings = {}
    filters.each do |f|
      settings["#{f.setting}"] = "#{f.val}"
    end

    # List of the available filter params.
    setting_names = ["search", "title", "post", "offset", "bookmarks", "services", "bulkreply"]

    setting_names.each do |s|
      if params[s.to_sym].blank?
        # Test to see if we are clearing the search text.
        unless params[:clear_search].to_s === "true" && s === "search"
          # We're NOT resetting the search text, just getting the param value.
          params[s.to_sym] = settings[s.to_s]
        else
          # If we're resetting the search text.
          params[:search] = ""
          
          # Persist the reset.
          if current_user.filter_settings.where(setting: "#{s}").count > 0
            filter = current_user.filter_settings.find_by(setting: "#{s}")
          else
            filter = current_user.filter_settings.new
          end
          
          filter.setting = "search"
          filter.val = nil
          filter.save
        end
      else
        if current_user.filter_settings.where(setting: "#{s}").count > 0
          filter = current_user.filter_settings.find_by(setting: "#{s}")
        else
          filter = current_user.filter_settings.new
        end
        # Populate/update the rec and save.
        filter.setting = s
        unless s === "services"
          eval("filter.val = params[:#{s}]")
        else
          unless params[:services].blank?
            if params[:services][0] === "["
              filter.val = eval(params[:services])
            else
              filter.val = params[:services].split(",")
            end
          end
          
          # services = params[:services].split(",")
          # filter.val = services
        end          
        filter.save
      end
    end
    
    @settings = params

    # Inconsistencies in persisting and retrieving the array, so we'll look at several factors and convert based on results.
#     unless @settings[:services].class.to_s === "Array"
#       unless @settings[:services].blank?
#         if @settings[:services][0] === "["
#           @settings[:services] = eval(@settings[:services])
#         else
#           @settings[:services] = @settings[:services].split(",")
#         end
#       end
#     end

    unless params.blank?
      @listings = filter(params)
    else
      @listings = @listings.page(page_num).order("id DESC")
    end
    
    # User bids.
    @user_bids = Bid.where(user_id: current_user.id).pluck(:listing_id)
    
    # Default message templates.
    @templates = BidMessageDefault.all
    winning = current_user.bids.where("won_at IS NOT NULL").group(:message_type).calculate(:count, :message_id)
    
    @best_msg = {}
    
    unless winning.blank?
      if (winning["user"] > winning["template"] || winning["user"] === winning["template"] && winning["user"]) && winning["user"] != nil
        # User generated is most popular or there is a tie between most popular user and default templates.
        winner_id = current_user.bids.where(message_type: "user").group(:message_id).calculate(:maximum, :message_id)
        @best_msg["type"] = "user"
        @best_msg["id"] = winner_id.first[0]
      elsif winning["user"] === 0 && winning["template"] === "0"
        # No data.
        @best_msg["type"] = "user"
        @best_msg["id"] = 0
      else
        # Template is most popular.
        winner_id = current_user.bids.where(message_type: "template").group(:message_id).calculate(:maximum, :message_id)
        @best_msg["type"] = "template"
        @best_msg["id"] = winner_id.first[0]
      end
    end
    
    # User-made message templates.
    @user_templates = current_user.user_messages
    
    # Replies received from bulk-ready providers.
    @incoming_messages = current_user.incoming_messages.where(viewed: nil)
    
    # Check to see if there are messages for the user.
    msg = IncomingMessage.new
    msg.check(1, current_user.id)
    msg.check(3, current_user.id)
    
    @reddit_messages = current_user.incoming_messages.where(service_id: 1, viewed: nil).order("id DESC")
    @twitter_messages = current_user.incoming_messages.where(service_id: 3, viewed: nil).order("id DESC")
    @tokens = Token.where(user_id: current_user.id).pluck(:service_id)
    @filtered_count = @listings.total_count
    
    # Stats
    @added_today = Listing.where("created_at >= ?", Time.zone.now.beginning_of_day).count
    @currently_available = Listing.where("expired_at >= ?", Time.now).count
    @processed = Listing.count

    respond_to do |format|
      format.html { }
      format.js { }
      format.json {  }
      format.csv { send_data @listings.to_csv, filename: "listings-#{Date.today}-page#{page_num}.csv" }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #=============================================
  # Get listings
  #=============================================
  ##############################################
  ## TODOS
  ## [] Don't forget to add time constraints
  ##############################################
  def bookmark_toggle
    unless params[:listing_id].blank? || params[:status].blank?
      bookmark = ListingsUser.find_by(listing_id: params[:listing_id])
      
      if params[:status] == "false"
        # If we have a record, retrieve it.
        unless bookmark.blank?
          bookmark.destroy
        end  
      else
        # Don't create a new bookmark for this user/listing if one exists.
        if bookmark.blank?
          bookmark = ListingsUser.new
          bookmark.user_id = current_user.id
          bookmark.listing_id = params[:listing_id]
          bookmark.save
        end
      end
      render json: { success: true }, status: 200
    else
      render json: { success: false, message: "Please provide required parameters." }, status: 200
    end
  end
  
  def add_bid
    unless params[:listing_id].blank?
      bid = Bid.find_by(listing_id: params[:listing_id])
      
      render json: { success: true }, status: 200
    else
      render json: { success: false, message: "Please provide required parameters." }, status: 200
    end
  end
  
  def filter(params)
    queries = []
    query = ""
    bookmarks_query = ""
    bookmarks_count = current_user.listings.where(expired_at: nil).count
    services_query = ""
    page_num = params[:page] || 1
    
    if params[:services].class.to_s === "String"
      if params[:services][0] === "["
        service_arr = eval(params[:services])
      else
        service_arr = params[:services].split(",")
      end
    else
      service_arr = params[:services]
    end

    # build the services query
    unless service_arr.blank?
      services = service_arr.map { |s| "'#{s}'" }
      
      case params[:bulkreply]
        when "bulk"
          service_ids = Service.where("name in (#{services.join(",")}) AND bulkreply IS TRUE").pluck(:id)
          services_query = "service_id IN (#{service_ids.join(",")})"

        when "no_bulk"
          service_ids = Service.where("name in (#{services.join(",")}) AND bulkreply IS FALSE").pluck(:id)
          services_query = "service_id IN (#{service_ids.join(",")})"
        
        else
          service_ids = Service.where("name in (#{services.join(",")})").pluck(:id)
          services_query = "service_id IN (#{service_ids.join(",")})"
      end
    end

    # build title search query
    if params[:title].to_s === "true"
      queries <<  "title LIKE '%#{params[:search]}%'"
      # title_query = " OR title LIKE '%#{params[:search]}%'"
    end

    # build the post search query
    if params[:post].to_s === "true"
      queries << "descr LIKE '%#{params[:search]}%'"
      # post_query = " OR desc LIKE '%#{params[:search]}%'"
    end

    # build the bookmarks query
    unless params[:bookmarks].blank?
      if params[:bookmarks].to_s === "true"# && bookmarks_count > 0
         unless bookmarks_count === 0
          bookmarked = current_user.listings
          bookmarked_ids = []

          bookmarked.each do |b|
            bookmarked_ids << b.id  
          end

          # queries << "id IN (#{bookmarked_ids.join(",")})"
          bookmarks_query = "id IN (#{bookmarked_ids.join(",")})"

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :service %>
    <%= f.text_field :service %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :listed_at %>
    <%= f.datetime_select :listed_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
          <div class="col-md-8 col-md-offset-1" id="listings">
            <%- unless @listings.blank? -%>
        <h3>Listings (<%= number_with_delimiter(@filtered_count) %>)</h3>
              <table class="table">
              <thead>
                <th></th>
                <th><a href="#" class="sort-link update-filters<% if @sort_by === "service" %> active<% end %>" data-col="service" data-sort-direction="<% if @sort_by === "service" %><%= @sort_direction %><% else %>none<% end %>">Service <span class="fa <% if @sort_by === "service" %><%= "fa-sort-amount-#{@sort_direction}" %><% else %>fa-sort<% end %>"></span></a></th>
                <th><a href="#" class="sort-link update-filters<% if @sort_by === "listed_at" %> active<% end %>" data-col="listed_at" data-sort-direction="<% if @sort_by === "listed_at" %><%= @sort_direction %><% else %>none<% end %>">Date <span class="fa <% if @sort_by === "listed_at" %><%= "fa-sort-amount-#{@sort_direction}" %><% else %>fa-sort<% end %>"></span></a></th>
                <th class="tbl-last-col"><a href="#" class="sort-link update-filters<% if @sort_by === "title" %> active<% end %>" data-col="title" data-sort-direction="<% if @sort_by === "title" %><%= @sort_direction %><% else %>none<% end %>">Job Title <span class="fa <% if @sort_by === "title" %><%= "fa-sort-amount-#{@sort_direction}" %><% else %>fa-sort<% end %>"></span></a></th>
              </thead>

              <tbody>
                <% bg_color = "ededed" %>
                <% @listings.each do |listing| %>
                <tr class="tbl-data-row" style="background-color: #<%= bg_color %>;">
                  <td class="tbl-cols listing-ctrl-btns" style="white-space: nowrap;" data-id="<%= listing.id %>">
                    <a href="javascript:void(0);" class="action-btns expand-rec" title="Show listing details."><%= image_tag "plus.png" %></a>
                    <a href="javascript:void(0);" class="action-btns collapse-rec" style="display: none;" title="Hide listing details."><%= image_tag "minus.png" %></a>

                    <%# Handle bookmarked listings. %>
                    <% display_icon = listing.users.first.nil? ? ["none","inline"] : ["inline","none"] %>
                    <a href="javascript:void(0);" class="action-btns save-listing" title="Save this listing.">
                      <%= image_tag "bookmark", class: "bookmarkers fa-bookmark", style: "display: #{display_icon[0]};" %><%= image_tag "bookmark_gray", class: "bookmarkers fa-bookmark-o", style: "display: #{display_icon[1]};" %>
                    </a>

                    <%# Handle bidding. %>
                    <% unless @user_bids.include? listing.id %>
                    <a href="#" class="job-bid-message-link" data-target="#job_bid_message_modal" data-toggle="modal" data-bulk="<%= listing.service.bulkreply %>" data-id="<%= listing.id %>" title="Bid on this job."><%= image_tag "hammer" %></a>
                    <% else %>
                    <small data-id="<%= listing.id %>"><%= image_tag "hammer_checked" %></small>
                    <% end %>

                  </td>
                  <td class="tbl-cols"><%= listing.service.name %><%= raw("<span style='font-size: 8.5pt;' title='When you are bidding on jobs from #{listing.service.name.titleize}, you can create one message and send it to all bookmarks that support bulk applying.'><br/>Supports bulk applying!</span>") if listing.service.bulkreply %></td>
                  <td class="tbl-cols"><%= listing.listed_at.strftime("%B %e, %Y") unless listing.listed_at.blank? %></td>
                  <td class="tbl-last-col"><a class="listing-link listing-title" href="<%= listing.url %>" data-id="<%= listing.id %>" target="_BLANK"><%= listing.title.truncate(65) %></a></td>
                </tr>
                <tr class="tbl-content-row" style="display: none; background-color: #e7f6f1;">
                  <td colspan="4" class="listings-content">
                    <pre style="width: 720px;" class="listing-desc"><%= simple_format( listing.descr.strip ).gsub(URI.regexp, '<a href="\0" target="_BLANK">\0</a>').html_safe %></pre>
                  </td>
                </tr>
                <% if bg_color === "ededed"
                  bg_color = "d6d6d6"
                else
                  bg_color = "ededed"
                end %>
                <% end %>
              </tbody>
            </table>
            <%- else -%>
            <div class="row">
              <div class="col-md-12"><h2>No listings found matching your criteria.</h2></div>
            </div>
            <%- end -%>
        </div>
    
      <%- unless @listings.blank? -%>
        <div class="col-md-12" style="text-align: center;" id="listings_pagination"><%= paginate @listings %></div>
      <%- end -%>
  </div>
</div>

app/views/listings/index.js.erb
var replacement_html = `<div class="row">
        <div class="col-md-8 col-md-offset-2" id="listings">
          <%- unless @listings.blank? -%>
          

          <h3>Listings</h3>
          <table class="table">
            <thead>
              <th></th>
              <th><a href="#" class="sort-link update-filters<% if @sort_by === "service" %> active<% end %>" data-col="service" data-sort-direction="<% if @sort_by === "service" %><%= @sort_direction %><% else %>none<% end %>">Service <span class="fa <% if @sort_by === "service" %><%= "fa-sort-amount-#{@sort_direction}" %><% else %>fa-sort<% end %>"></span></a></th>
              <th><a href="#" class="sort-link update-filters<% if @sort_by === "listed_at" %> active<% end %>" data-col="listed_at" data-sort-direction="<% if @sort_by === "listed_at" %><%= @sort_direction %><% else %>none<% end %>">Date <span class="fa <% if @sort_by === "listed_at" %><%= "fa-sort-amount-#{@sort_direction}" %><% else %>fa-sort<% end %>"></span></a></th>
              <th class="tbl-last-col"><a href="#" class="sort-link update-filters<% if @sort_by === "title" %> active<% end %>" data-col="title" data-sort-direction="<% if @sort_by === "title" %><%= @sort_direction %><% else %>none<% end %>">Job Title <span class="fa <% if @sort_by === "title" %><%= "fa-sort-amount-#{@sort_direction}" %><% else %>fa-sort<% end %>"></span></a></th>
            </thead>

            <tbody>
              <% bg_color = "ededed" %>
              <% @listings.each do |listing| %>
              <tr class="tbl-data-row" style="background-color: #<%= bg_color %>;">
                <td class="tbl-cols listing-ctrl-btns" data-id="<%= listing.id %>">
                  <a href="javascript:void(0);" class="action-btns expand-rec" title="Show listing details."><%= image_tag "plus.png" %></a>
                  <a href="javascript:void(0);" class="action-btns collapse-rec" style="display: none;" title="Hide listing details."><%= image_tag "minus.png" %></a>
                  
                  <%# Handle bookmarked listings. %>
                  <% display_icon = listing.users.first.nil? ? ["none","inline"] : ["inline","none"] %>
                  <a href="javascript:void(0);" class="action-btns save-listing" title="Save this listing.">
                    <%= image_tag "bookmark", class: "bookmarkers fa-bookmark", style: "display: #{display_icon[0]};" %><%= image_tag "bookmark_gray", class: "bookmarkers fa-bookmark-o", style: "display: #{display_icon[1]};" %>
                  </a>
                  
                  <%# Handle bidding. %>
                  <% unless @user_bids.include? listing.id %>
                  <a href="#" class="job-bid-message-link" data-target="#job_bid_message_modal" data-toggle="modal" data-bulk="<%= listing.service.bulkreply %>" data-id="<%= listing.id %>" title="Bid on this job."><%= image_tag "hammer" %></a>
                  <% else %>
                  <small data-id="<%= listing.id %>"><%= image_tag "hammer_checked" %></small>
                  <% end %>
                  
                </td>
                <td class="tbl-cols"><%= listing.service.name %><%= raw("<span style='font-size: 8.5pt;' title='When you are bidding on jobs from #{listing.service.name.titleize}, you can create one message and send it to all bookmarks that support bulk applying.'><br/>Supports bulk applying!</span>") if listing.service.bulkreply %></td>
                <td class="tbl-cols"><%= listing.listed_at.strftime("%B %e, %Y") unless listing.listed_at.blank? %></td>
                <td class="tbl-last-col"><a class="listing-link listing-title" href="<%= listing.url %>" data-id="<%= listing.id %>" target="_BLANK"><%= listing.title.truncate(65) %></a></td>
              </tr>
              <tr class="tbl-content-row" style="display: none; background-color: #e7f6f1;">
                <td colspan="4" class="listings-content">
                  <pre style="width: 720px;" class="listing-desc"><%= simple_format( listing.descr.strip ).gsub(URI.regexp, '<a href="\0" target="_BLANK">\0</a>').html_safe %></pre>
                </td>
              </tr>
              <% if bg_color === "ededed"
                bg_color = "d6d6d6"
              else
                bg_color = "ededed"
              end %>
              <% end %>
            </tbody>
          </table>
          <%- else -%>
          <div class="row">
            <div class="col-md-12"><h2>No listings found matching your criteria.</h2></div>
          </div>
          <%- end -%>
      </div>
    </div>
    <%- unless @listings.blank? -%>
    <div class="row">
      <div class="col-md-12" style="text-align: center;" id="listings_pagination"><%= paginate @listings, remote: true %></div>
    </div>
    <%- end -%>`

$("#listings_container").html(replacement_html);

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/reddit.html.erb
<h1>Reddit Results</h1>
<div><%= @json %></div>
<p>
  <% @json["data"]["children"].each do |j| %>
    <% j["data"].each do |item| %>
      <%= item["selftext"] %>
      <p><%#= i["title"] %></p>
      <br/><br/><hr/>
    <% end %>
  <% end %>
</p>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @listing.service %>
</p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @listing.desc %>
</p>

<p>
  <strong>Url:</strong>
  <%= @listing.url %>
</p>

<p>
  <strong>Listed at:</strong>
  <%= @listing.listed_at %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>