config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :filter_settings
  resources :user_messages
  resources :bid_message_defaults
  devise_for :users
  resources :listings
  resources :services
  resources :reports
  resources :job_bids
  
  get 'reddit', to: "listings#reddit"
  get 'bid/:range/report', to: "reports#bids"
  
  # get '/auth/:service', to: "services#connect_service_accounts"
  get '/auth/:service/callback', to: "services#connect_service_accounts"
  
  post 'save_credentials', to: "services#create_service_credentials"
  post 'service/accounts/new', to: "services#create_service_accounts"
  
  post 'listing/bookmark', to: "listings#bookmark_toggle"
  post 'listing/filter', to: "listings#listings_search_and_filter"
  
  post 'custom_message', to: "user_messages#create_user_message"
  
  delete 'delete_custom_message', to: "user_messages#delete_user_message"
  
  get 'incoming_messages', to: "incoming_messages#all_incoming"
  
  post 'messages/viewed', to: "incoming_messages#clear_messages"
  post 'message/viewed', to: "incoming_messages#mark_as_viewed"
  
  get 'job_bid_message', to: "job_bids#bid_message"
  get 'all_listings', to: "listings#all_listings"
  
  post 'log_bid', to: "job_bids#log_bid"
  
  # Test the validity of user Oauth tokens.
  post 'token_check', to: "services#check_oauth_tokens"
  
  # Toggle won_at for bids.
  post 'bid/won', to: "job_bids#toggle_won"
  
  get 'bids/today', to: "job_bids#today_bids"
  
  root 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_account_modal.html.erb
<div class="modal fade pg-show-modal" id="account_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Account</h4>
            </div>
            <div class="modal-body">
                <h1>Account Details</h1>
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#personal_details" data-toggle="tab">Personal Details</a>
                    </li>
                    <li>
                        <a href="#service_accounts" data-toggle="tab">Service Accounts</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="personal_details">
                        <label style="width: 100%;" for="account_email">Email:
                            <input type="text" class="form-control" style="width: 100%;" name="" id="account_email" placeholder="email">
                        </label>
                        <br />
                        <label style="width: 100%;" for="account_password">Password:
                            <input type="password" class="form-control" style="width: 100%;" name="" id="account_password" placeholder="password">
                        </label>
                        <br />
                        <label style="width: 100%;" for="account_password">Confirm Password:
                            <input type="password" class="form-control" style="width: 100%;" name="" id="confirm_account_password" placeholder="password">
                        </label>
                    </div>
                    <div class="tab-pane" id="service_accounts">
                        <% unless @tokens.include? 1 %>
                      <div style="margin-bottom: 20px;">
                        <div class="pull-right">
                          <%= link_to "/auth/reddit", class: "btn btn-default btn-sm" do %>
                            <span class="fa fa-plug"></span> Connect
                          <% end %> or 
<!--                           <a href="https://www.reddit.com/api/v1/authorize?client_id=<%= Rails.application.secrets.reddit_key %>&response_type=code&state=<%= current_user.id %>_rdt&redirect_uri=<%= Rails.application.secrets.callback_uri %>/reddit/callback&duration=permanent&scope=identity edit flair history mysubreddits privatemessages read" target="_BLANK" class="btn btn-default btn-sm"><span class="fa fa-plug"></span> Connect</a> or -->
<!--                      <a href="https://www.reddit.com/api/v1/authorize?client_id=<%= Rails.application.secrets.reddit_key %>&response_type=code&state=<%= current_user.id %>_rdt&redirect_uri=<%= Rails.application.secrets.callback_uri %>/rdt/callback&duration=permanent&scope=identity edit flair history modconfig modflair modlog modposts modwiki mysubreddits privatemessages read" target="_BLANK" class="btn btn-default btn-sm"><span class="fa fa-plug"></span> Connect</a> or -->
                          <a href="https://www.reddit.com/login" target="_BLANK" class="btn btn-primary btn-sm">+ Sign Up</a>
                        </div>
                        <label style="margin: 10px 0 10px 0;" for="">Reddit</label>
                          <p class="template-body">Reddit bridges communities and individuals with ideas, the latest digital trends, and breaking news (...okay, and maybe cats). Our mission is to help people discover places where they can be their true selves, and empower our community to flourish.</p>
<!--                         <input type="text" name="" id="" class="form-control" placeholder="username">
                        <input type="password" name="" id="" class="form-control" placeholder="password"> -->
                      </div>
                      <% end %>
                      <% unless @tokens.include? 2 %>
                      <div style="margin-bottom: 20px;">
                        <div class="pull-right">
                          <%= link_to "/auth/upwork", class: "btn btn-default btn-sm" do %>
                            <span class="fa fa-plug"></span> Connect
                          <% end %> or 

                          <a href="https://www.upwork.com/signup" target="_BLANK" class="btn btn-primary btn-sm">+ Sign Up</a>
                        </div>
                        <label style="margin: 10px 0 10px 0;" for="">UpWork</label>
                          <p class="template-body">Whether you need one writer or an entire team of programmers, we help you find the right experts to fuel your success. Our freelancing website lets you work effortlessly with freelancers anywhere. Say goodbye to business as usual.</p>
                      </div>
                      <% end %>
                      <% unless @tokens.include? 3 %>
                      <div style="margin-bottom: 20px;">
                        <div class="pull-right">
                          <%= link_to "/auth/twitter", class: "btn btn-default btn-sm" do %>
                            <span class="fa fa-plug"></span> Connect
                          <% end %> or 
                          <a href="https://twitter.com/signup" target="_BLANK" class="btn btn-primary btn-sm">+ Sign Up</a>
                        </div>
                        <label style="margin: 10px 0 10px 0;" for="">Twitter</label>
                          <p class="template-body">Twitter is an online news and social networking service where users post and interact with messages, "tweets," restricted to 140 characters. </p>
                      </div>
                      <% end %>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

app/views/partials/_job_bid_message.html.erb
<div class="modal fade pg-show-modal" id="job_bid_message_modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Messages</h4>
      </div>
      <div class="modal-body">
        <!--         <button class="btn btn-default pull-right create-usr-msg" type="button"><span class="fa fa-plus highlighted-icon"></span>&nbsp;New Template</button> -->
        <div class="leading modal-body-title">Message Templates</div>
        <ul class="list-group" id="message_templates_list_bid" style="height: 250px; overflow-y: scroll;">
          <% @templates.each do |tmpl| %>
          <%= link_to bid_message_default_path(tmpl), class: "bid-message-items", remote: true do %>
              <li class="list-group-item"<%= raw(' style="background-color: #D9EDF7;" title="Best converting template."') if @best_msg["type"] === "template" && @best_msg["id"] === tmpl.id %>>
                <h4 class="leading"><%= raw(' <span class="fa fa-star"></span>&nbsp;') if @best_msg["type"] === "template" && @best_msg["id"] === tmpl.id %><%= tmpl.title %></h4>
                <small class="template-body"><%= tmpl.body.truncate(200) %></small>
              </li>
            <% end %>
            <% end %>

              <% @user_templates.each do |tmpl| %>
          <%= link_to user_message_path(tmpl), class: "bid-message-items", data: {id: tmpl.id}, remote: true do %>
                  <li class="list-group-item"<%= raw(' style="background-color: lime;"') if tmpl.id = @best_msg["type"] === "user" && @best_msg["id"] === tmpl.id %>>
                    <h4 class="leading"><% if @best_msg["type"] === "user" && @best_msg["id"] === tmpl.id %><span class="fa fa-star" title="Best converting template."></span>&nbsp;<% end %><%= tmpl.title %></h4>
                    <small class="template-body"><%= tmpl.body.truncate(200) %></small>
                  </li>
          <% end %>
                <% end %>
        </ul>

        <span id="bid_subj_group">
          <input type="hidden" id="message_id" value="" />
          <input type="hidden" id="message_type" value="custom" />
          <label for="bid_message_subj">Subject (used by Reddit)</label>
          <input type="text" name="" id="bid_message_subj" class="form-control" />
        </span>
        <span id="bid_message_group">
          <label for="bid_message_text">Message</label>
          <textarea id="bid_message_text" cols="30" rows="4" style="width: 100%;"></textarea>
        </span>
        <span id="bid_twitter_group">
          <label for="bid_message_twitter">Twitter Message (140 chars max)</label>
          <input type="text" name="" id="bid_message_twitter" class="form-control" />
          <span class="pull-right"><small id="bid_message_twitter_char_count">0</small> <small>chars</small></span>
        </span>
        <div class="panel panel-default" id="message_preview_panel" style="display: none;">
          <div class="panel-heading" id="message_preview_title"></div>
          <div class="panel-body" id="message_preview_body"></div>
        </div>
        <div class="panel panel-default" id="message_edit_panel" style="display: none;">
          <div class="panel-heading" id="message_edit_title">
            <span class="fa fa-times close-message-preview pull-right"></span>Edit message template
          </div>
          <div class="panel-body" id="message_edit_body">
            <label for="message_edit_title_input">Title</label>
            <input type="text" name="" id="message_edit_title_input" class="form-control" />
            <label for="message_editor_textarea">Message</label>
            <textarea name="" id="message_editor_textarea" style="width: 100%;" rows="10"></textarea>
            <button class="btn btn-info pull-right" style="margin-top: 10px;" type="button" id="save_cloned_template" data-template-id=""><span class="fa fa-floppy-o"></span>&nbsp;Save</button>
            <input type="hidden" name="" id="message_edit_mode" value="" />
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="clipboard_copy_btn" data-clipboard-target="#bid_message_text">Copy to clipboard</button>
        <button type="button" class="btn btn-default" data-type="" data-id="" data-dismiss="modal" id="job_bid_btn"></button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_job_bid_report_modal.html.erb
<div class="modal fade pg-show-modal" id="job_bid_report_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Jobs</h4>
            </div>
            <div class="modal-body">
                <h1>Job Bid Report</h1>
                <label class="control-label">
<!--                     <input type="radio" name="bid_report" value="7days" checked /> -->
                    <a href="/bid/7/report" class="btn btn-default"><span class="fa fa-binoculars"></span> View Report</a> Bids made in the last 7 days
                </label>
                <br />
                <label class="control-label">
                    <a href="/bid/30/report" class="btn btn-default"><span class="fa fa-binoculars"></span> View Report</a> Bids made in the last 30 days
<!--                     <input type="radio" name="bid_report" value="30days" />        Bids made in the last 30 days -->
                </label>
                <br />
                <label class="control-label">
                  <a href="/bid/all/report" class="btn btn-default"><span class="fa fa-binoculars"></span> View Report</a> All bids made
<!--                     <input type="radio" name="bid_report" value="all" />        All bids made -->
                </label>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/partials/_message_templates_modal.html.erb
<div class="modal fade pg-show-modal" id="message_templates_modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Messages</h4>
      </div>
      <div class="modal-body">
        <button class="btn btn-default pull-right create-usr-msg" type="button"><span class="fa fa-plus highlighted-icon"></span>&nbsp;New Template</button>
        <div class="leading modal-body-title">Message Templates</div>
        <ul class="list-group message-templates-list" id="message_templates_list">
          <% @templates.each do |tmpl| %>
            <li class="list-group-item">
              <span class="pull-right"><button class="btn btn-default edit-message-template" type="button" data-id="<%= tmpl.id%>"><span class="fa fa-pencil-square-o highlighted-icon"></span>&nbsp;Copy & Edit</button>
              </span>
              <h4 class="leading"><%= tmpl.title %></h4>
              <!--                     <div class="radio radio-default">
                      <span class="pull-right fa fa-eye preview-message-template" data-id="<%= tmpl.id %>"></span>
                      <span class="pull-right fa fa-pencil-square-o edit-message-template" data-id="<%= tmpl.id %>"></span>
                      <input type="radio" name="items" id="tmpl_<%= tmpl.id %>" value="item<%= tmpl.id %>"><label style=""><%= tmpl.title %></label>
                    </div> -->
              <small class="template-body"><%= tmpl.body.truncate(200) %></small>
            </li>
            <% end %>
          
            <% @user_templates.each do |tmpl| %>
              <li class="list-group-item">
                <span class="pull-right">
                  <div class="btn-group" role="group">
                    <button class="btn btn-sm btn-default clone-usr-msg" type="button" data-id="<%= tmpl.id%>" title="Copy & edit message"><span class="fa fa-clone highlighted-icon"></span></button>
                    <button class="btn btn-sm btn-default edit-usr-msg" type="button" data-id="<%= tmpl.id%>" title="Edit message"><span class="fa fa-pencil-square-o highlighted-icon"></span></button>
                    <button class="btn btn-sm btn-default del-usr-msg" type="button" data-id="<%= tmpl.id%>" title="Delete message"><span class="fa fa-minus highlighted-icon"></span></button>
                  </div>
                  
                </span>
                <h4 class="leading"><%= tmpl.title %></h4>
                <small class="template-body"><%= tmpl.body.truncate(200) %></small>
              </li>
              <% end %>
        </ul>
        <div class="panel panel-default" id="message_preview_panel" style="display: none;">
          <div class="panel-heading" id="message_preview_title"></div>
          <div class="panel-body" id="message_preview_body"></div>
        </div>
        <div class="panel panel-default" id="message_edit_panel" style="display: none;">
          <div class="panel-heading" id="message_edit_title">
            <span class="fa fa-times close-message-preview pull-right"></span>Edit message template
          </div>
          <div class="panel-body" id="message_edit_body">
            <label for="message_edit_title_input">Title</label>
            <input type="text" name="" id="message_edit_title_input" class="form-control" />
            <label for="message_editor_textarea">Message</label>
            <textarea name="" id="message_editor_textarea" style="width: 100%;" rows="10"></textarea>
            <button class="btn btn-info pull-right" style="margin-top: 10px;" type="button" id="save_cloned_template" data-template-id=""><span class="fa fa-floppy-o"></span>&nbsp;Save</button>
            <input type="hidden" name="" id="message_edit_mode" value="" />
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_messages_modal.html.erb
<div class="modal fade pg-show-modal" id="messages_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Notifications</h4>
            </div>
          
            <div class="modal-body" id="message_replies_modal_body">
            <%- if @reddit_messages.count + @twitter_messages.count < 1 -%>
              <div class="alert alert-success" role="alert"><span class="fa fa-thumbs-o-up"></span>&nbsp;No new messages.</div>
            <%- else -%>
              <%- if @reddit_messages.count > 0 -%>
              <div class="panel panel-default" id="reddit_reply_panel">
                  <div class="panel-heading" id="message_reply_title"><button type="button" class="btn btn-xs btn-default pull-right" id="clear_all_reddit_btn">Clear All</button>Reddit&nbsp;<span class="badge" id="reddit_message_count"><%= @reddit_messages.count %></span></div>
                  <div class="panel-body" id="reddit_reply_body">
                    <ul class="list-group">
                        <% @reddit_messages.each do |msg| %>
                        <li class="list-group-item"><a href="https://www.reddit.com/message/unread" target="_BLANK" class="btn btn-xs btn-default pull-right reply-on-reddit-btn" data-id="<%= msg.id %>">Reply on Reddit</a>
                          <%= msg.title %>
                          <br/><small><%= msg.body %></small>
                        </li>
                        <% end %>
                    </ul>
                  </div>
              </div>
              <% end %>
              
              <%- if @twitter_messages.count > 0 -%>
              <div class="panel panel-default" id="twitter_reply_panel">
                  <div class="panel-heading" id="message_reply_title"><button type="button" class="btn btn-xs btn-default pull-right" id="clear_all_twitter_btn">Clear All</button>Twitter&nbsp;<span class="badge" id="twitter_message_count">1</span></div>
                  <div class="panel-body" id="message_reply_body">
                    <ul class="list-group">
                        <% @twitter_messages.each do |msg| %>
                        <li class="list-group-item"><a href="https://twitter.com/" target="_BLANK" class="btn btn-xs btn-default pull-right reply-on-twitter-btn" data-id="<%= msg.id %>">Reply on Twitter</a>
                        <%= msg.title %>
                        <br/><small><%= msg.body %></small>
                      </li>       
                        <% end %>
                    </ul>
                  </div>
              </div>
            <% end %>
          <%- end -%>
          </div>
          
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/partials/_notifications_modal.html.erb
<div class="modal fade pg-show-modal" id="notifications_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Notifications</h4>
            </div>
            <div class="modal-body" id="notifications_modal_body">
                <button type="button" class="btn btn-default" style="margin-bottom: 20px;" id="clear_notifications_btn">Clear Notifications</button>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-danger"></span><span class="fa fa-warning"></span>&nbsp;Cannot retrieve messages from Reddit.</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/partials/_renew_tokens_modal.html.erb
<div class="modal fade pg-show-modal" id="token_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Renew your application access</h4>
            </div>
            <div class="modal-body">
<!--                 <div class="container col-md-12"> -->
                  <div class="row">
                    <div class="col-md-12">
                      <h2>Account Tokens</h2>
                      <% unless @tokens.include? 1 %>
                      <div style="margin-bottom: 20px;">
                        <div class="pull-right">
                          <%= link_to "/auth/reddit", class: "btn btn-default btn-sm" do %>
                            <span class="fa fa-plug"></span> Connect
                          <% end %> or 
<!--                           <a href="https://www.reddit.com/api/v1/authorize?client_id=<%#= Rails.application.secrets.reddit_key %>&response_type=code&state=<%= current_user.id %>_rdt&redirect_uri=<%= Rails.application.secrets.callback_uri %>/reddit/callback&duration=permanent&scope=identity edit flair history mysubreddits privatemessages read" target="_BLANK" class="btn btn-default btn-sm"><span class="fa fa-plug"></span> Connect</a> or -->
<!--                      <a href="https://www.reddit.com/api/v1/authorize?client_id=<%#= Rails.application.secrets.reddit_key %>&response_type=code&state=<%= current_user.id %>_rdt&redirect_uri=<%= Rails.application.secrets.callback_uri %>/rdt/callback&duration=permanent&scope=identity edit flair history modconfig modflair modlog modposts modwiki mysubreddits privatemessages read" target="_BLANK" class="btn btn-default btn-sm"><span class="fa fa-plug"></span> Connect</a> or -->
                          <a href="https://www.reddit.com/login" target="_BLANK" class="btn btn-primary btn-sm">+ Sign Up</a>
                        </div>
                        <label style="margin: 10px 0 10px 0;" for="">Reddit</label>
                          <p class="template-body">Reddit bridges communities and individuals with ideas, the latest digital trends, and breaking news (...okay, and maybe cats). Our mission is to help people discover places where they can be their true selves, and empower our community to flourish.</p>
<!--                         <input type="text" name="" id="" class="form-control" placeholder="username">
                        <input type="password" name="" id="" class="form-control" placeholder="password"> -->
                      </div>
                      <% end %>
                      <% unless @tokens.include? 2 %>
<!--                       <div style="margin-bottom: 20px;">
                        <div class="pull-right">
                          <%#= link_to "/auth/upwork", class: "btn btn-default btn-sm" do %>
                            <span class="fa fa-plug"></span> Connect
                          <%# end %> or 

                          <a href="https://www.upwork.com/signup" target="_BLANK" class="btn btn-primary btn-sm">+ Sign Up</a>
                        </div>
                        <label style="margin: 10px 0 10px 0;" for="">UpWork</label>
                          <p class="template-body">Whether you need one writer or an entire team of programmers, we help you find the right experts to fuel your success. Our freelancing website lets you work effortlessly with freelancers anywhere. Say goodbye to business as usual.</p>
                      </div> -->
                      <% end %>
                      <% unless @tokens.include? 3 %>
                      <div style="margin-bottom: 20px;">
                        <div class="pull-right">
                          <%= link_to "/auth/twitter", class: "btn btn-default btn-sm" do %>
                            <span class="fa fa-plug"></span> Connect
                          <% end %> or 
                          <a href="https://twitter.com/signup" target="_BLANK" class="btn btn-primary btn-sm">+ Sign Up</a>
                        </div>
                        <label style="margin: 10px 0 10px 0;" for="">Twitter</label>
                          <p class="template-body">Twitter is an online news and social networking service where users post and interact with messages, "tweets," restricted to 140 characters. </p>
                      </div>
                      <% end %>
                    </div>
                  </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/partials/_upwork-icon-svg.html.erb
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.79 12" style="width: 24px; height: 24px; padding-top: 8px;"><defs><style>.cls-1{fill:#333;}</style></defs><title>2804-16_Website_IconsforTeach_Upwork</title><path id="_Compound_Path_" data-name="&lt;Compound Path&gt;" class="cls-1" d="M13,1A3.82,3.82,0,0,0,9.3,4.13,16.77,16.77,0,0,1,7.4,0H5.5V5A1.8,1.8,0,0,1,1.9,5V0H0V5A3.7,3.7,0,1,0,7.4,5V4.17A16.14,16.14,0,0,0,8.77,6.45L7.59,12H9.53l0.85-4A4.81,4.81,0,0,0,13,8.73a3.83,3.83,0,0,0,3.79-3.89A3.81,3.81,0,0,0,13,1Zm0,5.74a3.38,3.38,0,0,1-2.13-.85l0.19-.76v0c0.14-.81.57-2.18,2-2.18a1.9,1.9,0,0,1,1.9,1.9A2,2,0,0,1,13,6.78Z"/></svg>