config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :filter_settings
  resources :user_messages
  resources :bid_message_defaults
  devise_for :users
  resources :listings
  resources :services
  resources :reports
  resources :job_bids
  
  get 'reddit', to: "listings#reddit"
  get 'bid/:range/report', to: "reports#bids"
  
  # get '/auth/:service', to: "services#connect_service_accounts"
  get '/auth/:service/callback', to: "services#connect_service_accounts"
  
  post 'save_credentials', to: "services#create_service_credentials"
  post 'service/accounts/new', to: "services#create_service_accounts"
  
  post 'listing/bookmark', to: "listings#bookmark_toggle"
  post 'listing/filter', to: "listings#listings_search_and_filter"
  
  post 'custom_message', to: "user_messages#create_user_message"
  
  delete 'delete_custom_message', to: "user_messages#delete_user_message"
  
  get 'incoming_messages', to: "incoming_messages#all_incoming"
  
  post 'messages/viewed', to: "incoming_messages#clear_messages"
  post 'message/viewed', to: "incoming_messages#mark_as_viewed"
  
  get 'job_bid_message', to: "job_bids#bid_message"
  get 'all_listings', to: "listings#all_listings"
  
  post 'log_bid', to: "job_bids#log_bid"
  
  # Test the validity of user Oauth tokens.
  post 'token_check', to: "services#check_oauth_tokens"
  
  # Toggle won_at for bids.
  post 'bid/won', to: "job_bids#toggle_won"
  
  get 'bids/today', to: "job_bids#today_bids"
  
  root 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_message.rb
# == Schema Information
#
# Table name: user_messages
#
#  id                     :integer          not null, primary key
#  title                  :string
#  body                   :text
#  bid_message_default_id :integer
#  user_id                :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class UserMessage < ApplicationRecord
  belongs_to :user
end

app/controllers/user_messages_controller.rb
class UserMessagesController < ApplicationController
  before_action :set_user_message, only: [:show, :edit, :update, :destroy]

  # GET /user_messages
  # GET /user_messages.json
  def index
    @user_messages = UserMessage.all
  end

  # GET /user_messages/1
  # GET /user_messages/1.json
  def show
    unless params[:id].blank?
      @message = UserMessage.find(params[:id])
      @message_id = params[:message_id]

      respond_to do |format|
        format.js {}
        format.html {}
      end
    end
  end

  # GET /user_messages/new
  def new
    @user_message = UserMessage.new
  end

  # GET /user_messages/1/edit
  def edit
  end

  # POST /user_messages
  # POST /user_messages.json
  def create
    @user_message = UserMessage.new(user_message_params)

    respond_to do |format|
      if @user_message.save
        format.html { redirect_to @user_message, notice: 'User message was successfully created.' }
        format.json { render :show, status: :created, location: @user_message }
      else
        format.html { render :new }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_messages/1
  # PATCH/PUT /user_messages/1.json
  def update
    respond_to do |format|
      if @user_message.update(user_message_params)
        format.html { redirect_to @user_message, notice: 'User message was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_message }
      else
        format.html { render :edit }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_messages/1
  # DELETE /user_messages/1.json
  def destroy
    @user_message.destroy
    respond_to do |format|
      format.html { redirect_to user_messages_url, notice: 'User message was successfully destroyed.' }
      format.json { head :no_content }
    end
    
    redirect_to :root_path
  end
  
  def create_user_message
    unless params[:title].blank? || params[:body].blank?
      # Eval the params to determine if this is a create or edit action.
      case "#{params[:mode]}"
        when "new"
          msg = UserMessage.new
        when "edit"
          unless params[:template_id].blank?
            puts "Finding a rec..."
            msg = UserMessage.find(params[:template_id])
          else
            msg = UserMessage.new
          end
        else
          msg = UserMessage.new
      end
      
      msg.title = params[:title]
      msg.body = params[:body]
      unless params[:template_id].blank? || params[:mode] === "edit"
        msg.bid_message_default_id = params[:template_id]
      end
      msg.user_id = current_user.id
      msg.save
      
      render json: { success: true, custom_msg: msg, msg_truncated_body: msg.body.truncate(200), id: msg.id }, status: 200
    else
      render json: { success: false, message: "Please provide required parameters." }, status: 200
    end
  end
  
  def delete_user_message
    unless params[:id].blank?
      del = UserMessage.find(params[:id])
      
      unless del.blank?
        del.destroy
        del.save
      end
      
      msg = current_user.user_messages
      render json: { success: true, custom_msg: msg }, status: 200
    else
      render json: { success: false, message: "Please provide required parameters." }, status: 200
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_message
      @user_message = UserMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_message_params
      params.require(:user_message).permit(:title, :body, :bid_message_default_id)
    end
end

app/helpers/user_messages_helper.rb
module UserMessagesHelper
end

app/views/user_messages/_form.html.erb
<%= form_for(user_message) do |f| %>
  <% if user_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_message.errors.count, "error") %> prohibited this user_message from being saved:</h2>

      <ul>
      <% user_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :bid_message_default_id %>
    <%= f.number_field :bid_message_default_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_messages/edit.html.erb
<h1>Editing User Message</h1>

<%= render 'form', user_message: @user_message %>

<%= link_to 'Show', @user_message %> |
<%= link_to 'Back', user_messages_path %>

app/views/user_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Messages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Bid message default</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_messages.each do |user_message| %>
      <tr>
        <td><%= user_message.title %></td>
        <td><%= user_message.body %></td>
        <td><%= user_message.bid_message_default_id %></td>
        <td><%= link_to 'Show', user_message %></td>
        <td><%= link_to 'Edit', edit_user_message_path(user_message) %></td>
        <td><%= link_to 'Destroy', user_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Message', new_user_message_path %>

app/views/user_messages/new.html.erb
<h1>New User Message</h1>

<%= render 'form', user_message: @user_message %>

<%= link_to 'Back', user_messages_path %>

app/views/user_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @user_message.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @user_message.body %>
</p>

<p>
  <strong>Bid message default:</strong>
  <%= @user_message.bid_message_default_id %>
</p>

<%= link_to 'Edit', edit_user_message_path(@user_message) %> |
<%= link_to 'Back', user_messages_path %>

app/views/user_messages/show.js.erb
var msg = `<%= @message.body.to_s %>`.replace(/&#39;/g, "'");
$("#bid_message_text").val(msg);
$("#message_id").val(<%= @message_id %>);
$("#message_type).val("user");