config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :filter_settings
  resources :user_messages
  resources :bid_message_defaults
  devise_for :users
  resources :listings
  resources :services
  resources :reports
  resources :job_bids
  
  get 'reddit', to: "listings#reddit"
  get 'bid/:range/report', to: "reports#bids"
  
  # get '/auth/:service', to: "services#connect_service_accounts"
  get '/auth/:service/callback', to: "services#connect_service_accounts"
  
  post 'save_credentials', to: "services#create_service_credentials"
  post 'service/accounts/new', to: "services#create_service_accounts"
  
  post 'listing/bookmark', to: "listings#bookmark_toggle"
  post 'listing/filter', to: "listings#listings_search_and_filter"
  
  post 'custom_message', to: "user_messages#create_user_message"
  
  delete 'delete_custom_message', to: "user_messages#delete_user_message"
  
  get 'incoming_messages', to: "incoming_messages#all_incoming"
  
  post 'messages/viewed', to: "incoming_messages#clear_messages"
  post 'message/viewed', to: "incoming_messages#mark_as_viewed"
  
  get 'job_bid_message', to: "job_bids#bid_message"
  get 'all_listings', to: "listings#all_listings"
  
  post 'log_bid', to: "job_bids#log_bid"
  
  # Test the validity of user Oauth tokens.
  post 'token_check', to: "services#check_oauth_tokens"
  
  # Toggle won_at for bids.
  post 'bid/won', to: "job_bids#toggle_won"
  
  get 'bids/today', to: "job_bids#today_bids"
  
  root 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bid_message_default.rb
# == Schema Information
#
# Table name: bid_message_defaults
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BidMessageDefault < ApplicationRecord
end

app/controllers/bid_message_defaults_controller.rb
class BidMessageDefaultsController < ApplicationController
  before_action :set_bid_message_default, only: [:show, :edit, :update, :destroy]

  # GET /bid_message_defaults
  # GET /bid_message_defaults.json
  def index
    @bid_message_defaults = BidMessageDefault.all
  end

  # GET /bid_message_defaults/1
  # GET /bid_message_defaults/1.json
  def show
    unless params[:id].blank?
      @message = BidMessageDefault.find(params[:id])
      @message_id = params[:message_id]
            
      respond_to do |format|
        format.js {}
        format.html {}
      end
    end
  end

  # GET /bid_message_defaults/new
  def new
    @bid_message_default = BidMessageDefault.new
  end

  # GET /bid_message_defaults/1/edit
  def edit
  end

  # POST /bid_message_defaults
  # POST /bid_message_defaults.json
  def create
    @bid_message_default = BidMessageDefault.new(bid_message_default_params)

    respond_to do |format|
      if @bid_message_default.save
        format.html { redirect_to @bid_message_default, notice: 'Bid message default was successfully created.' }
        format.json { render :show, status: :created, location: @bid_message_default }
      else
        format.html { render :new }
        format.json { render json: @bid_message_default.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bid_message_defaults/1
  # PATCH/PUT /bid_message_defaults/1.json
  def update
    respond_to do |format|
      if @bid_message_default.update(bid_message_default_params)
        format.html { redirect_to @bid_message_default, notice: 'Bid message default was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid_message_default }
      else
        format.html { render :edit }
        format.json { render json: @bid_message_default.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bid_message_defaults/1
  # DELETE /bid_message_defaults/1.json
  def destroy
    @bid_message_default.destroy
    respond_to do |format|
      format.html { redirect_to bid_message_defaults_url, notice: 'Bid message default was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid_message_default
      @bid_message_default = BidMessageDefault.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_message_default_params
      params.require(:bid_message_default).permit(:title, :body)
    end
end

app/helpers/bid_message_defaults_helper.rb
module BidMessageDefaultsHelper
end

app/views/bid_message_defaults/_form.html.erb
<%= form_for(bid_message_default) do |f| %>
  <% if bid_message_default.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bid_message_default.errors.count, "error") %> prohibited this bid_message_default from being saved:</h2>

      <ul>
      <% bid_message_default.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bid_message_defaults/edit.html.erb
<h1>Editing Bid Message Default</h1>

<%= render 'form', bid_message_default: @bid_message_default %>

<%= link_to 'Show', @bid_message_default %> |
<%= link_to 'Back', bid_message_defaults_path %>

app/views/bid_message_defaults/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bid Message Defaults</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bid_message_defaults.each do |bid_message_default| %>
      <tr>
        <td><%= bid_message_default.title %></td>
        <td><%= bid_message_default.body %></td>
        <td><%= link_to 'Show', bid_message_default %></td>
        <td><%= link_to 'Edit', edit_bid_message_default_path(bid_message_default) %></td>
        <td><%= link_to 'Destroy', bid_message_default, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid Message Default', new_bid_message_default_path %>

app/views/bid_message_defaults/new.html.erb
<h1>New Bid Message Default</h1>

<%= render 'form', bid_message_default: @bid_message_default %>

<%= link_to 'Back', bid_message_defaults_path %>

app/views/bid_message_defaults/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bid_message_default.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @bid_message_default.body %>
</p>

<%= link_to 'Edit', edit_bid_message_default_path(@bid_message_default) %> |
<%= link_to 'Back', bid_message_defaults_path %>

app/views/bid_message_defaults/show.js.erb
var msg = `<%= @message.body.to_s %>`.replace(/&#39;/g, "'");
$("#bid_message_text").val(msg);
$("#message_id").val(<%= @message_id %>);
$("#message_type").val("template");